<?php

/**
 * @file
 * Integration module for NYS Universal Navigation.
 *
 * Defines two blocks, NYS uNav Header and NYS uNav Footer.
 * Can also be integrated directly into a theme.
 * See:  https://github.com/ny/universal-navigation.
 */

/**
 * Implements hook_block_info().
 */
function nys_unav_block_info() {
  $blocks = array(
    'nys_unav_header' => array(
      // The name that will appear in the block list.
      'info' => t('NYS uNav Header'),
      // Disable caching in MVP.
      'cache' => DRUPAL_NO_CACHE,
    ),
    'nys_unav_footer' => array(
      // The name that will appear in the block list.
      'info' => t('NYS uNav Footer'),
      // Disable caching in MVP.
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function nys_unav_block_view($delta = '') {
  switch ($delta) {
    case 'nys_unav_header':
      // Set block subject and content.
      $block['subject'] = t('NYS uNav Header');
      $block['content'] = nys_unav_header();
      return $block;

    case 'nys_unav_footer':
      // Set block subject and content.
      $block['subject'] = t('NYS uNav Footer');
      $block['content'] = nys_unav_footer();
      return $block;

  }
}

/**
 * Implements hook_page_build().
 *
 * Add uNav header and footer to the page_top and page_bottom regions
 * automatically if Drupal variable nys_unav_auto is TRUE.
 * But don't add uNav if on an administrative page.
 */
function nys_unav_page_build(&$page) {
  // Skip menu if not Auto or on administrative page.
  if (!variable_get('nys_unav_auto', FALSE) || path_is_admin(current_path())) {
    return;
  }
  // Performance: Skip this entirely for AJAX requests.
  // Code from admin_menu module, seemed like a good idea.
  if (strpos($_GET['q'], 'js/') === 0) {
    return;
  }
  $page['page_top']['nys_unav'] = array(
    '#weight' => -1000,
    '#theme' => 'nys_unav_header',
  );
  $page['page_bottom']['nys_unav'] = array(
    '#weight' => 1000,
    '#theme' => 'nys_unav_footer',
  );
}

/**
 * Implements hook_theme().
 */
function nys_unav_theme() {
  return array(
    'nys_unav_header' => array(
      'template' => 'nys-unav-header',
      'variables' => array(),
    ),
    'nys_unav_footer' => array(
      'template' => 'nys-unav-footer',
      'variables' => array(),
    ),
  );
}

/**
 * Non-hook function to generate header block content.
 *
 * Returns raw html content suitable for printing in theme.
 */
function nys_unav_header() {
  $header = theme('nys_unav_header');
  return $header;
}

/**
 * Non-hook function to generate footer block content.
 *
 * Returns raw html content suitable for printing in theme.
 */
function nys_unav_footer() {
  $footer = theme('nys_unav_footer');
  return $footer;
}
